import { SignInButton, useUser } from "@clerk/nextjs";
import dayjs from "dayjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { LoadingPage } from "~/Components/Loading";
import { type RouterOutputs, api } from "~/utils/api";

const ProfilePage: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser()

  const {data, isLoading} = api.profile.getUserByUserName.useQuery({
    userName: "t3dotgg"
  })

  if(isLoading) return <LoadingPage/>

  if(!data) return <div>404</div>

  if (!userLoaded) return <div />


  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div/>
      </main>
    </>
  )
}

export default ProfilePage
