import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser()
  
  if(!user) return null;

  return (
    <div className="flex">
       {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={user.profileImageUrl}
        alt="Profile image"
        className="h-14 w-14 rounded-full"
        />
    </div>
  )

}

const Home: NextPage = () => {
  const {data} = api.post.getAll.useQuery();
  const user = useUser()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div>
          {!user.isSignedIn && <SignInButton/>}
          {!!user.isSignedIn && <CreatePostWizard/>}
        </div>
      </main>
    </>
  );
};

export default Home;
